### ISSUE TITLE
Node server trying to cache a scss file, returning typeName error

### ISSUE THREAD

**Issue by jasonbarone** [NodeSquarespace/node-squarespace-server#143]
``` 
sqs-log Get local cache for key => page-sass-modules-_overlay.scss.html
> sqs-log Get local cache for key => page-sass-modules-_overlay.scss.json
> sqs-log Store local cache for key => page-sass-modules-_overlay.scss.json
> sqs-log Store local cache for key => page-sass-modules-_overlay.scss.html
> sqs-log Get local cache for key => page-sass-modules-_overlay.scss.html
/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:903
    typeName = pageJson.collection.typeName;
                                  ^

TypeError: Cannot read property 'typeName' of undefined
    at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:903:35)
    at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:457:23)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:230:29
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:325:13
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:248:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)

```

Not really sure why the node server is trying to grab JSON from a Sass file though. It happens when I open Chrome Inspector on a static page. Not really sure how else to try to pinpoint it.

**Comment by kitajchuk** [comment]
This is weird. Maybe related to source maps... not sure though.

**Comment by jasonbarone** [comment]
I've been digging around for a few hours, still not sure what else I can provide. The only thing I'm seeing constantly is a browser sync error that's repeating itself. I'm not even using --reload though. 
```
browser-sync-client.2.9.11.js:2 GET http://localhost:5050/browser-sync/socket.io/?EIO=3&transport=polling&t=1446129909079-0 net::ERR_CONNECTION_REFUSED
```

**Comment by jasonbarone** [comment]
I think I may have pinpointed it. A Chrome Extension called Emmet LiveStyle which is popular among Squarespace users (mainly due to me recommending it) seems like it's causing some issues with css files. Disabling the extension seemed to fix the crashing issue. I'm still getting a Browser Sync client error in Firefox though. I'm now looking through extensions. Should I open a new issue for Emmet LiveStyle?

**Comment by kitajchuk** [comment]
Okay, cool. Glad its at least a specific use case scenario :)

**Comment by jasonbarone** [comment]
Created new issue for this: https://github.com/NodeSquarespace/node-squarespace-server/issues/145
