### ISSUE TITLE
Server crashing on initial page load

### ISSUE THREAD

**Issue by aapljack** [NodeSquarespace/node-squarespace-server#147]
I have just updated to the latest version of node-squarespace-server and am having an issue with the server crashing right as the first page loads. I get through the squarespace login step, the page loads and the server immediately crashes. I have uninstalled and reinstalled node-squarespace-server. I have also run through the troubleshooting items with no luck. Any insight?

```
> sqs-log Preloaded local cache
> sqs-log Squarespace server running localhost:5050
> sqs-log Logging into Squarespace...
> sqs-log ...Logged in to Squarespace
> sqs-log Fetching data from Squarespace...
> sqs-log ...Fetched data from Squarespace
> sqs-log Get local cache for key => page-homepage.html
> sqs-log Get local cache for key => page-homepage.json
> sqs-log Get local cache for key => page-scripts-jquery.fancylike.js.html
> sqs-log Get local cache for key => page-scripts-jquery.fancylike.js.json

TypeError: Cannot read property 'error' of undefined
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:283:27)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by kitajchuk** [comment]
Yes, for some reason your Javascript file is trying to load like a Squarespace page... How are you loading that jQuery fancylike script?

**Comment by aapljack** [comment]
I have it linked via a relative path at the bottom of the document.

```
<script src="/scripts/jquery.js"></script>
<script src="/scripts/jquery.fancylike.js"></script>
<script src="/scripts/app.js"></script>
```
If I take out all this JS, I run into this error.
```
> sqs-log Squarespace server running localhost:5050
> sqs-log Logging into Squarespace...
> sqs-log ...Logged in to Squarespace
> sqs-log Fetching data from Squarespace...
> sqs-log ...Fetched data from Squarespace
> sqs-log Get local cache for key => page-homepage.html
> sqs-log Get local cache for key => page-homepage.json
> sqs-log Store local cache for key => page-homepage.json
> sqs-log Store local cache for key => page-homepage.html
> sqs-log Get local cache for key => page-homepage.html
> sqs-log Get local cache for key => page-assets-fonts-icomoon.woff2-vuoy06--.html
> sqs-log Get local cache for key => page-assets-fonts-icomoon.woff2-vuoy06--.json
> sqs-log Store local cache for key => page-assets-fonts-icomoon.woff2-vuoy06--.json
> sqs-log Store local cache for key => page-assets-fonts-icomoon.woff2-vuoy06--.html
> sqs-log Get local cache for key => page-assets-fonts-icomoon.woff2-vuoy06--.html

TypeError: Cannot read property 'typeName' of undefined
    at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:903:35)
    at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:457:23)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:230:29
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:325:13
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:248:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1009:12)
```

**Comment by planetargon** [comment]
I have the server working again. Just realized the fancylike js wasn't in my squarespace directory. Fixed a couple other broken links to assets and I am back in business.

Thanks for the help.

**Comment by aapljack** [comment]
I have the server working again. Just realized the fancylike js wasn't in my squarespace directory. Fixed a couple other broken links to assets and I am back in business.

Thanks for the help.

**Comment by kitajchuk** [comment]
Ha! Glad you got it figured out!
