### ISSUE TITLE
Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by skrichten** [NodeSquarespace/node-squarespace-server#155]
Just started getting this error.  I have already tried running sqs buster.

C:\Users\SleekDigital\AppData\Roaming\nvm\v4.2.3\node_modules\node-squa
respace-server\node_modules\node-squarespace-middleware\squarespace-mid
dleware.js:109
            error = (json.error ? json.error : error);
                         ^

TypeError: Cannot read property 'error' of undefined
    at Request._callback (C:\Users\SleekDigital\AppData\Roaming\nvm\v4.
2.3\node_modules\node-squarespace-server\node_modules\node-squarespace-
middleware\squarespace-middleware.js:109:26)
    at self.callback (C:\Users\SleekDigital\AppData\Roaming\nvm\v4.2.3\
node_modules\node-squarespace-server\node_modules\request\request.js:19
8:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\SleekDigital\AppData\Roaming\nv
m\v4.2.3\node_modules\node-squarespace-server\node_modules\request\requ
est.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketOnEnd (_http_client.js:288:9)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)

**Comment by kitajchuk** [comment]
Yeah - I think this is related to the request timing out. Still need to figure out what to do about it.

**Comment by skrichten** [comment]
Confirmed... This magically went away, so it was probably just Squarespace being slow for awhile.

**Comment by kitajchuk** [comment]
Yeah - I'm working on some better error handling for the middleware based on Squarespace's response types. Ideally it will successfully log errors without blowing up for all known scenarios on the next  release.
