### ISSUE TITLE
TypeError: Cannot read property 'links' of null

### ISSUE THREAD

**Issue by jasonbarone** [NodeSquarespace/node-squarespace-server#167]
I think I had this issue in the past once. Hard to know what's causing it. I have 3 navigation areas in Squarespace, one of which is all folders and external links. 

Here's the error:

```
> sqs-log Get local cache for key => page-homepage.html
/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:1120
    var navContext = getNavigationContextItems( navigation, (pageLinks || navigation.links), pageJson ),
                                                                                    ^

TypeError: Cannot read property 'links' of null
    at getNavigationContext (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:1120:85)
    at replaceNavigations (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:1006:23)
    at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:516:16)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:272:29
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:376:13
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:300:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1036:10)
```

**Comment by vicodinchik** [comment]
I have some issue

**Comment by kitajchuk** [comment]
I think this has something to do with using a `<squarespace:navigation>` tag without a `navigationId` attribute. Any thoughts on that?
