### ISSUE TITLE
ReferenceError: sqsLogger is not defined

### ISSUE THREAD

**Issue by cyponthemic** [NodeSquarespace/node-squarespace-server#171]
Hi support,

I have tried to run sqs server, but I am getting a error each time, see log below.

Thank you in advance for your help - let me know if you need more information from me.

Alex Chavet
```
MacBook-Pro-de-Alex:template cyponthemic$ sqs server

/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:851
                                sqsLogger.log( "warn", ("Issue compiling less 
                                ^
ReferenceError: sqsLogger is not defined
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:851:33
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/index.js:23:26
    at Object.finish [as _finish] (/usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/parser.js:666:28)
    at subFinish (/usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/import-visitor.js:87:47)
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/import-visitor.js:103:25
    at fileParsedFunc (/usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/parser.js:82:17)
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/parser.js:89:29
    at tryPathIndex (/usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/index.js:247:21)
    at callback.type (/usr/local/lib/node_modules/node-squarespace-server/node_modules/less/lib/less/index.js:233:29)
    at Object.oncomplete (evalmachine.<anonymous>:107:15)

```

**Comment by kitajchuk** [comment]
Yo - sorry about that. I had one bad ref to the logger variable in there after an update. This commit fixes it: bcbe04fa5fc8278dd27ccd659065fef0715855f3. If you update from npm you should get the latest which is 0.4.24.
